# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/openjdk:latest'
    steps:
      - checkout # check out the code
      - run: echo "hello cruel world" #run the echo command
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/my-reports

          